Code review of the TSE
carloshdelreal/design-teardown pull request #1
Opened 2019-06-17 17:11 UTC by carloshdelreal

project complete, the grey scale heatmap and the dummy text

2019-06-18 01:03 UTC, Torres-ssf commented
Hi there team...
You got most of the things right. But before I give this project a 👍, we need to make some changes.
- [ ] All content should be wrapped with `<main>` HTML tags
- [ ] Every children of main should be a `<section>` HTML tag pair
- [ ] Every children of section should be an `<article>` HTML tag pair

- [ ] Your page must use the `<nav>` for the navbar. The navbar must have 7 separate containers (div is recommended) representing the icons and links.

- [ ]  The four articles with 50% width (the main articles) must have an image in top left corner (like the original page) with the title of an article under it. Use a small container (div) to represent the image.

- [ ] Three articles with a width of 33%.

- [ ] Kindly create some links for the footer. They should cover the central part of the footer, both horizontally and vertically. It should have an unorganized list `<ul>`

Please kindly make these changes and submit for code review again.

2019-06-18 01:13 UTC, Torres-ssf requested changes

2019-06-18 01:13 UTC, Torres-ssf commented on index.html
> +            <div class="nav-header">
Use a `nav` with 7 containers inside it.

2019-06-18 01:13 UTC, Torres-ssf commented on index.html
> +        <div class="section">
Each one of the 4 main articles should have an image in the top left corner with title of an article under it.

2019-06-18 01:13 UTC, Torres-ssf commented on index.html
> +            <div>
Your page must have a section with 3 articles of 33% width each. Delete one of these columns and give the 3 articles the same width.

2019-06-18 20:24 UTC, carloshdelreal commented
___Fix the live version of your page.___
Answer:
Once the development branch be merged with the master branch, then you will see the changes in the live page, that is because github pages only can be activated for the master branch

2019-06-18 21:42 UTC, bellom requested changes
Hi @carloshdelreal @ViriCruz, 
It not necessary you make use of gh-pages before you could create live link, kindly checkout this [video tutorials](https://www.loom.com/share/f7688bd6dbb54ae2a4e80a621fa7665d)

I can see you did a good job doing all the corrections pointed out from previous review but you misunderstood one and you left one out.
1. *You misunderstood :point_right:*  ` All content should be wrapped with <main> HTML tags`.
   What the reviewer is telling you is: navbar should be inside `nav tag` and page content inside `main tag`, read about best HTML5 practice [here](https://www.themelocation.com/best-html5-practices/)

2. *Leftout:* Reviewer made mention that the navbar must have 7 separate containers (div is recommended) representing the icons and links.

Kindly do these two things and your :+1: await you and submit for code review again.

2019-06-20 18:20 UTC, carloshdelreal commented
We have already added the 7 containers to the navbar and distribute the semantic elements as is suggested in the best HTML5 practice [here](https://www.themelocation.com/best-html5-practices/)

![Screenshot 2019-06-20 13 14 54](https://user-images.githubusercontent.com/8964341/59871891-2f393d00-935e-11e9-975c-7b48aee0e8db.png)

2019-06-20 19:07 UTC, bellom reviewed
Hi @carloshdelreal @ViriCruz,
The tags elements are now looking good.

![image](https://user-images.githubusercontent.com/31897434/59874823-1e58ed80-9397-11e9-8c44-cb7da4edcc3e.png)

My suggestion would be to improve the navbar with 7 divs, and also work on the UI, all the projects will be included in your portfolio.
checkout an example [here](https://nazeh.github.io/design-teardown/)
Goodluck in the next project....

2019-06-20 21:50 UTC, bellom commented
Awesome, you don't need to submit another code review go ahead and merge to master and also fill the project completion form .

2019-06-20 21:54 UTC, merged